name: blendedlearningstarterkit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.0
  cloud_firestore: ^0.12.9
  firebase_auth: ^0.14.0+2
  firebase_core: ^0.4.0+8
  firebase_storage: ^3.0.8
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:     
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
          style: normal


flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/3PhasesBL.png